language: go
go:
  - 1.11.x
install:
  # Fetch dependencies
  - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x dep
  - mv dep $GOPATH/bin/dep
script:
  - ./configure
  # Run tests
  - make test
  - go build
sudo: false
before_install:
  # Make sure it works for forks.
  - ln -s $HOME/gopath/src/github.com/${TRAVIS_REPO_SLUG///oauth2_proxy/} $HOME/gopath/src/github.com/pusher
before_deploy:
  - DIR=oauth2_proxy-$(echo $TRAVIS_TAG | sed s/v//).0.linux-amd64.go${TRAVIS_GO_VERSION}
  - mkdir ${DIR}
  - cp oauth2_proxy ${DIR}
  - tar -czf ${DIR}.tar.gz ${DIR}
go_import_path: github.com/pusher/oauth2_proxy
notifications:
  email: true
deploy:
  provider: releases
  api_key:
    secure: "JcP+eEvHMGdf/qsF94BmhM95RGFRMBquM28ND7S9oPM07u9PpTG+T6i1jETXG89MXKAnO4J7hRn+lb8Q5A7HWtONxONzlragJ1N1K6tRpoom4xWNMGkCqAAwAIMPPtEyIHx8vQ5gsaCBdSpsIhSMCOcYCF4ay7kzviv6qSzgnjH7Tsi2nHQoYQGMejlv9mxTdWZqVe6oWDn/LdwGC7x7+ErfF8vTEvrp5ZRCDZI6zoxHNk/li2miZsEEEYWRJtiEn2taYE8PpSlzaLxjMUQZW3V/7vjjjp4lQ6j+U4H8jJVFqR+Y7vvP7yrdjsLarTRyh5V4BL+EgLATogKEodkBV1hgRSHG6ZJxp50zlxUPz3VZxyxfhtJvZwKRLB3tozyM0j9JSBgI7CjEnWIkWBFRehpPdKm3qAvvwf2sGJHtmmloTst27jeDCSwg7uiTiEEX5vd28c5T+Ogkenf5YmWB9AKz+GeUAGu/nxZN6b1vhXB7vnMz81/rKNN/ebXtI2ysYNCBKSJD78imJf7CLvn0wEfo7NpXwpjzy+fw96yQwffCpUq1eWucotqRafEdIonArPac2ceXNwYhcrQ1ib4kWGwx29R1csnwsrmHSHDhZrE1QPW2gocU9hwD7lJL/E3g57mX6sH3ijoD4/KTQjfPkX3Y0CGY6Kx/QzqvpKaQVdA="
  file_glob: true
  file: oauth2_proxy-*.tar.gz
  skip_cleanup: true
  on:
    repo: criteo-forks/oauth2_proxy
    tags: true